### ISSUE TITLE
Need for release or at least exe file in repository

### ISSUE THREAD

**Issue by SoroushJM** [parsa1102/metricConvertor#1]
چرا مثل ادم کامپیل نکردی بشه بازش کرد 
یکی برای لینوکس کامپایل کن 
یکی برای ویندوز
فکر کردی اون hr  می شینه کدت رو می خونه ؟😂😂

**Comment by parsa1102** [comment]
اون hr بنده خدا که قراره اینو بخونه 😂😂😂

**Comment by SoroushJM** [comment]
@parsa1102 
باید بخونه 😂😂
